import os

os.makedirs("dist", exist_ok=True)

svg = """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="200">

    <rect width="100%" height="100%" fill="#0d1117"/>

    <text x="40" y="45"
          fill="white"
          font-size="26"
          font-family="Arial">
        GitHub Fish
    </text>

    <text x="40" y="80"
          fill="#58a6ff"
          font-size="18">
        Generated by GitHub Actions
    </text>

    <!-- Thân cá -->
    <ellipse cx="220" cy="130" rx="45" ry="25" fill="#00BFFF"/>

    <!-- Đuôi -->
    <polygon points="175,130 145,110 145,150"
             fill="#00BFFF"/>

    <!-- Mắt -->
    <circle cx="245" cy="122" r="4" fill="white"/>
    <circle cx="245" cy="122" r="2" fill="black"/>

    <!-- Bong bóng -->
    <circle cx="285" cy="110" r="5"
            fill="none"
            stroke="#8FD3FF"
            stroke-width="2"/>

    <circle cx="305" cy="90" r="8"
            fill="none"
            stroke="#8FD3FF"
            stroke-width="2"/>

</svg>
"""

with open("dist/github-contribution-grid-fish.svg", "w", encoding="utf-8") as f:
    f.write(svg)

print("Fish SVG generated!")
