import os

os.makedirs("dist", exist_ok=True)

svg = """<svg xmlns="http://www.w3.org/2000/svg" width="800" height="200">
<rect width="100%" height="100%" fill="#0d1117"/>

<text x="40" y="40"
fill="white"
font-size="26"
font-family="Arial">
🐟 GitHub Fish
</text>

<text x="40" y="90"
fill="#58a6ff"
font-size="18">
This SVG was generated by GitHub Actions
</text>

<text x="40" y="140"
fill="#58a6ff"
font-size="40">
><(((('>
</text>

</svg>
"""

with open("dist/github-contribution-grid-fish.svg", "w", encoding="utf-8") as f:
    f.write(svg)

print("Fish SVG generated!")
